<?php

namespace Inky\CourseBundle\Entity\InkyChap;

use Doctrine\ORM\EntityRepository;

/**
 * InkyChapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InkyChapRepository extends EntityRepository
{
	public function getFirstChap($course)
	{
		$query = $this	->createQueryBuilder('c')
							->addSelect('c')
						->leftJoin('c.lesson', 'l')
							->addSelect('l')
						->where('l.course = :course')
						->orderBy('c.orderId', 'ASC')
						->setMaxResults( 1 )
						->setParameter('course',$course)
						->getQuery()
						->getOneOrNullResult();
		return $query;
	}
	
}
