<?php

namespace Inky\CourseBundle\Entity\InkyChap;

use Doctrine\ORM\EntityRepository;

/**
 * InkyChapAdvancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InkyChapAdvancementRepository extends EntityRepository
{
	public function getLastChap($course, $user)
	{
		$query = $this	->createQueryBuilder('a')
							->addSelect('a')
						->leftJoin('a.inkychap', 'c')
							->addSelect('c')
						->leftJoin('c.lesson', 'l')
							->addSelect('l');
						
		$query = $query ->where($query->expr()->andX(	$query->expr()->eq('l.course', ':course'),
														$query->expr()->eq('a.user', ':user'),
														$query->expr()->eq('a.completed', ':completed')
										)
								)
						->orderBy('c.orderId', 'DESC')
						->setMaxResults( 1 )
						->setParameter( 'course',$course)
						->setParameter( 'user', $user)
						->setParameter( 'completed', true)
						->getQuery()
						->getOneOrNullResult();

		return $query;
	}
	public function getLessonAdvancement($lesson, $user)
	{
		$query = $this	->createQueryBuilder('a')
							->addSelect('a')
						->leftJoin('a.inkychap', 'c')
							->addSelect('c');
						
		$query = $query ->where($query->expr()->andX(	$query->expr()->eq('c.lesson', ':lesson'),
														$query->expr()->eq('a.user', ':user'),
														$query->expr()->eq('a.completed', ':completed')
										)
								)
						->orderBy('c.orderId', 'DESC')
						->setParameter( 'lesson',$lesson)
						->setParameter( 'user', $user)
						->setParameter( 'completed', true)
						->getQuery()
						->getResult();

		return $query;
	}

}
