<?php

namespace Inky\CourseBundle\Entity\InkyChap;

use Doctrine\ORM\EntityRepository;

/**
 * InkyVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InkyVideoRepository extends EntityRepository
{
}
