<?php

namespace Inky\CourseBundle\Entity\InkyChap;

use Doctrine\ORM\EntityRepository;

/**
 * InkyTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InkyTextRepository extends EntityRepository
{
}
