<?php

namespace Inky\QuizBundle\Entity\Answer;

use Doctrine\ORM\EntityRepository;

/**
 * McAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class McAnswerRepository extends EntityRepository
{
}
