parameters:
    inky_forum.forum.inky_extension.class: Inky\ForumBundle\Twig\InkyExtension

services:
    inky.twig.inky_extension:
        class: %inky_forum.forum.inky_extension.class%
        tags:
            - { name: twig.extension }