parameters:
#    inky_forum.example.class: Inky\ForumBundle\Example

services:
#    inky_forum.example:
#        class: %inky_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
