<?php

namespace Inky\CourseBundle\Entity\Course;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
	public function getCourses($filter)
	{
		if ($filter === null) 
		{
		
		$query = $this->createQueryBuilder('c')
		->leftJoin('c.image', 'i')
			->addSelect('i')
		->leftJoin('c.tags', 'tags')
			->addSelect('tags')
		->where('c.isPublic = 1')
		->orderBy('c.date', 'DESC')
		->getQuery()
		->getResult();
		
		return $query;
		}
	}
	
	public function searchCourse($search)
	{
		$query = $this	->createQueryBuilder('c')
						->select('DISTINCT c')
						->leftJoin('c.tags', 'tags')
							->addSelect('tags');
		$result = $query->where($query->expr()->ORx(	$query->expr()->LIKE('tags.tagLabel', ':search'),
														$query->expr()->LIKE('c.title', ':search'))
								)
						->setParameter('search','%'.$search.'%')
						->getQuery()
						->getResult();
		return $result;
	}
}
