<?php

namespace Inky\CourseBundle\Entity\Course;

use Doctrine\ORM\EntityRepository;

/**
 * SubscribeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribeRepository extends EntityRepository
{
}
