<?php

namespace Inky\CourseBundle\Entity\Lesson;

use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
	public function getLessons($courseId, $user = null)
	{
		$query = 	$this->createQueryBuilder('l')
					->leftJoin('l.tags', 't')
						->addSelect('t')
					->where('l.isPublic = 1')
					->where('l.course ='.$courseId)
					->orderBy('l.orderid', 'ASC')
					->getQuery()
					->getResult();
		
		return $query;
	}
	

}
