<?php

namespace Inky\QuizBundle\Entity\Question;

use Doctrine\ORM\EntityRepository;

/**
 * TfQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TfQuestionRepository extends EntityRepository
{
}
