#Course routing
inky_presentation:
  pattern: /index
  defaults: { _controller: InkyCourseBundle:Course:index }

course_view:
  pattern: /course-presentation/{course}
  defaults: { _controller: InkyCourseBundle:Course:viewCourse }
  requirements:
    course:   \d+

courses_list:
  pattern: /courses-{section}
  defaults: { _controller: InkyCourseBundle:Course:showCourses, section:learn }
  requirements:
    section: learn|teach

course_administration:
  pattern: /course-{course}/admin
  defaults: { _controller: InkyCourseBundle:Course:adminCourse }
  requirements:
    course:   \d+

course_subscribe:
  pattern: /course-{course}/subscribe
  defaults: { _controller: InkyCourseBundle:Course:subscribeCourse }
  requirements:
    course:   \d+

course_content:
  pattern: course-{course}/
  defaults: { _controller: InkyCourseBundle:Course:viewCourseContent }
  requirements:
    course:   \d+

alt_course_content:
  pattern: /course-{course}/inkychap-{inkychap}
  defaults: { _controller: InkyCourseBundle:Course:viewAltCourseContent }
  requirements:
    course:   \d+

course_acess_chap_content:
  pattern: /inkychap-{inkychap}
  defaults: { _controller: InkyCourseBundle:InkyChap:viewInkyChap }
  requirements:
    course:   \d+

inkychap_mock:
  pattern: /inkychap-

course_new:
  pattern: /course/new
  defaults: { _controller: InkyCourseBundle:Course:addCourse }

course_edit:
  pattern: /course-{course}/edit
  defaults: { _controller: InkyCourseBundle:Course:editCourse }
  requirements:
    id:   \d+

course_group:
  pattern: /{course}/groups
  defaults: { _controller: InkyCourseBundle:Course:viewGroup }
  requirements:
    id:   \d+

course_group_edit:
  pattern: /group/{group}/edit
  defaults: { _controller: InkyCourseBundle:Course:editGroup }
  requirements:
    id:   \d+

course_add_group:
  pattern: /{course}/group/new
  defaults: { _controller: InkyCourseBundle:Course:addGroup }
  requirements:
    id:   \d+

course_delete:
  pattern: /course/{id}/delete
  defaults: { _controller: InkyCourseBundle:Course:delete }
  requirements:
    id:   \d+

#Lesson routing
lesson_statistics:
  pattern: /lesson/{lesson}/stats
  defaults: { _controller: InkyCourseBundle:Lesson:stats}
  requirements:
    page:   \d+

lesson_new:
  pattern: /lesson/new/{course}
  defaults: { _controller: InkyCourseBundle:Lesson:newLesson }
  requirements:
    course:   \d+

lesson_view:
  pattern: /lesson/{lesson}
  defaults: { _controller: InkyCourseBundle:Lesson:viewLesson }
  requirements:
    lesson:   \d+

lesson_edit:
  pattern: /lesson/{lesson}/edit
  defaults: { _controller: InkyCourseBundle:Lesson:editLesson }
  requirements:
    id:   \d+

lesson_delete:
  pattern: /lesson/{lesson}/delete
  defaults: { _controller: InkyCourseBundle:Lesson:delete }
  requirements:
    lesson:   \d+

lesson_ask:
  pattern: /lesson/{lesson}/ask
  defaults: { _controller: InkyCourseBundle:Lesson:ask }
  requirements:
    id:   \d+

lesson_statistics:
  pattern: /lesson/{lesson}/statistics
  defaults: { _controller: InkyCourseBundle:Lesson:statistics }
  requirements:
    id:   \d+

lesson_documentation:
  pattern: /{lesson}/documentation
  defaults: { _controller: InkyCourseBundle:Lesson:documentation }
  requirements:
    id:   \d+

#InkyChapter Routing
inkychap_add:
  pattern: /{lesson}/chap/new
  defaults: { _controller: InkyCourseBundle:InkyChap:addInkyChap }
  requirements:
    id:   \d+

inky_video_add:
  pattern: /{lesson}/Video/new
  defaults: { _controller: InkyCourseBundle:InkyChap:addInkyVideo }
  requirements:
    id:   \d+

inky_text_add:
  pattern: /{lesson}/Text/new
  defaults: { _controller: InkyCourseBundle:InkyChap:addInkyText }
  requirements:
    id:   \d+

inky_chap_statistics:
  pattern: /InkyChap/{inkychap}/stats
  defaults: { _controller: InkyCourseBundle:InkyChap:stats}
  requirements:
    page:   \d+

#Search Routing
general_search:
    pattern: /search/{search}
    defaults: {_controller: InkyCourseBundle:Course:generalSearch, search:null }
