parameters:
#    inky_course.example.class: Inky\CourseBundle\Example

services:
#    inky_course.example:
#        class: %inky_course.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
