<?php

namespace Inky\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	// In the controler we select only one of those, not so good WILL NEED SOME WORK
	public function getLastMessageUser($thread)
	{
		$query = $this	->createQueryBuilder('m')
						->leftJoin('m.user','u')
							->addSelect('u')
						->where('m.isDeleted = 0 AND m.thread = '.$thread->getId())
						->orderBy('m.id', 'DESC')
						->setMaxResults( 1 )
						
						->getQuery()
						->getOneOrNullResult();
					
		return $query;
	}
}
