<?php

namespace Inky\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PointActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointActionRepository extends EntityRepository
{
}
