<?php

namespace Inky\CourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LessonStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonStatusRepository extends EntityRepository
{
public function getLessonStatus($lessonId, $userId)
	{
		$query = 	$this->createQueryBuilder('lS');
		$result = $query->where($query->expr()->andX(	$query->expr()->eq('lS.lesson', ':lessonId'),
														$query->expr()->eq('lS.user', ':userId'))
							)
					->setParameter('userId', $userId)
					->setParameter('lessonId', $lessonId)
					->getQuery()
					->getResult();
		
			return $result;
	}
}
