<?php

namespace Inky\QuizBundle\Entity\UserAnswer;

use Doctrine\ORM\EntityRepository;

/**
 * InputUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputUserRepository extends EntityRepository
{
}
