<?php

namespace Inky\QuizBundle\Entity\UserAnswer;

use Doctrine\ORM\EntityRepository;

/**
 * McUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class McUserRepository extends EntityRepository
{
}
