<?php

namespace Inky\QuizBundle\Entity\UserAnswer;

use Doctrine\ORM\EntityRepository;

/**
 * UserAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAnswerRepository extends EntityRepository
{
	public function getQuestions()
	{
		$qb = $this	->createQueryBuilder('a')
					->where('a.publication = 1');
					return $qb;
	}
}
